In [ ]:
import math
import numpy as np
import cv2
image = cv2.imread('R.jpg')
m,n,v = image.shape
gray_image = np.zeros((m,n),np.uint8)
image_onezeroes = np.zeros((m,n),np.uint8)
image_onezeroes2 = np.zeros((m,n),np.uint8)
print(m,n,v)
dummy = 0
for i in range(m):
    for j in range(n):
        for k in range(v):
            dummy = dummy + image[i][j][k]
        gray_image[i][j] = math.floor(dummy/3)
        dummy = 0
for t in range(m):
    for u in range(n):
        image_onezeroes[t][u] = (gray_image[t][u])/255
for v in range(m):
    for w in range(n):
        if(gray_image[v][w] >= 128):
            image_onezeroes2[v][w] = 1
        else:
            image_onezeroes2[v][w] = 0
print("color image pixels")
print(image) 
print("gray image pixels")  
print(gray_image)
print("one/zero image pixels")
print(image_onezeroes)
print("one/zero image2 pixels")
print(image_onezeroes2)

cv2.imshow("original",image)
cv2.waitKey(0)
cv2.imshow('gray',gray_image)
cv2.waitKey(0)
cv2.imshow('zerosones',image_onezeroes)
cv2.waitKey(0)
cv2.imshow('zerosones2',image_onezeroes)
cv2.waitKey(0)
cv2.imshow('grayimage + zerosoneimage ',gray_image + image_onezeroes)
cv2.waitKey(0)
cv2.imshow('grayimage + zerosoneimage2 ',gray_image + image_onezeroes2)
cv2.waitKey(0)
cv2.imshow('grayimage + 20 ',gray_image + 20)
cv2.waitKey(0)
cv2.destroyAllWindows()

2160 3840 3
color image pixels
[[[20 32 38]
  [20 32 38]
  [21 33 39]
  ...
  [54 41 33]
  [55 42 34]
  [55 42 34]]

 [[19 31 37]
  [20 32 38]
  [21 33 39]
  ...
  [54 41 33]
  [55 42 34]
  [55 42 34]]

 [[20 32 38]
  [20 32 38]
  [21 33 39]
  ...
  [55 42 34]
  [55 42 34]
  [54 41 33]]

 ...

 [[45 74 89]
  [45 74 89]
  [45 74 89]
  ...
  [21 37 50]
  [18 34 47]
  [16 32 45]]

 [[45 74 89]
  [45 74 89]
  [44 73 88]
  ...
  [27 40 56]
  [22 35 49]
  [18 31 45]]

 [[44 73 88]
  [43 72 87]
  [43 72 87]
  ...
  [32 45 61]
  [26 39 53]
  [21 34 48]]]
gray image pixels
[[30 30 31 ... 42 43 43]
 [29 30 31 ... 42 43 43]
 [30 30 31 ... 43 43 42]
 ...
 [69 69 69 ... 36 33 31]
 [69 69 68 ... 41 35 31]
 [68 67 67 ... 46 39 34]]
one/zero image pixels
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
one/zero image2 pixels
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 